# Generated by Django 4.0.4 on 2022-06-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiestand',
            name='hourly_sales',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
